name: flutterinstagramclone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+11
  hive_flutter: ^1.1.0
  hive: ^2.0.6
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  firebase_database: ^9.0.8
  firebase_storage: ^10.2.9
  cloud_firestore: ^3.1.10
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  shimmer: ^2.0.0
  device_info_plus: ^3.2.2
  firebase_messaging: ^11.2.11
  flutter_local_notifications: ^9.4.0
  flutter_styled_toast: ^2.0.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
